package com.ridvan.passportlib


enum class Country(
    val countryAlphaCode: String,
    val countryName: String
) {
    AFGHANISTAN("af", "Afghanistan"),
    ALBANIA("al", "Albania"),
    ALGERIA("dz", "Algeria"),
    ANDORRA("ad", "Andorra"),
    ANGOLA("ao", "Angola"),
    ANTIGUA_AND_BARBUDA("ag", "Antigua and Barbuda"),
    ARGENTINA("ar", "Argentina"),
    ARMENIA("am", "Armenia"),
    AUSTRALIA("au", "Australia"),
    AUSTRIA("at", "Austria"),
    AZERBAIJAN("az", "Azerbaijan"),
    BAHAMAS("bs", "Bahamas"),
    BAHRAIN("bh", "Bahrain"),
    BANGLADESH("bd", "Bangladesh"),
    BARBADOS("bb", "Barbados"),
    BELARUS("by", "Belarus"),
    BELGIUM("be", "Belgium"),
    BELIZE("bz", "Belize"),
    BENIN("bj", "Benin"),
    BHUTAN("bt", "Bhutan"),
    BOLIVIA("bo", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("ba", "Bosnia and Herzegovina"),
    BOTSWANA("bw", "Botswana"),
    BRAZIL("br", "Brazil"),
    BRUNEI("bn", "Brunei"),
    BULGARIA("bg", "Bulgaria"),
    BURKINA_FASO("bf", "Burkina Faso"),
    BURUNDI("bi", "Burundi"),
    CAMBODIA("kh", "Cambodia"),
    CAMEROON("cm", "Cameroon"),
    CANADA("ca", "Canada"),
    CAPE_VERDE("cv", "Cape Verde"),
    CENTRAL_AFRICAN_REPUBLIC("cf", "Central African Republic"),
    CHAD("td", "Chad"),
    CHILE("cl", "Chile"),
    CHINA("cn", "China"),
    COLOMBIA("co", "Colombia"),
    COMOROS("km", "Comoros"),
    CONGO("cg", "Congo"),
    CONGO_DEMOCRATIC_REPUBLIC("cd", "Congo (Dem. Rep.)"),
    COSTA_RICA("cr", "Costa Rica"),
    COTE_DIVOIRE("ci", "Cote d'Ivoire (Ivory Coast)"),
    CROATIA("hr", "Croatia"),
    CUBA("cu", "Cuba"),
    CYPRUS("cy", "Cyprus"),
    CZECH_REPUBLIC("cz", "Czech Republic"),
    DENMARK("dk", "Denmark"),
    DJIBOUTI("dj", "Djibouti"),
    DOMINICA("dm", "Dominica"),
    DOMINICAN_REPUBLIC("do", "Dominican Republic"),
    ECUADOR("ec", "Ecuador"),
    EGYPT("eg", "Egypt"),
    EL_SALVADOR("sv", "El Salvador"),
    EQUATORIAL_GUINEA("gq", "Equatorial Guinea"),
    ERITREA("er", "Eritrea"),
    ESTONIA("ee", "Estonia"),
    ESWATINI("sz", "Eswatini"),
    ETHIOPIA("et", "Ethiopia"),
    FIJI("fj", "Fiji"),
    FINLAND("fi", "Finland"),
    FRANCE("fr", "France"),
    GABON("ga", "Gabon"),
    GAMBIA("gm", "Gambia"),
    GEORGIA("ge", "Georgia"),
    GERMANY("de", "Germany"),
    GHANA("gh", "Ghana"),
    GREECE("gr", "Greece"),
    GRENADA("gd", "Grenada"),
    GUATEMALA("gt", "Guatemala"),
    GUINEA("gn", "Guinea"),
    GUINEA_BISSAU("gw", "Guinea-Bissau"),
    GUYANA("gy", "Guyana"),
    HAITI("ht", "Haiti"),
    HONDURAS("hn", "Honduras"),
    HONG_KONG("hk", "Hong Kong"),
    HUNGARY("hu", "Hungary"),
    ICELAND("is", "Iceland"),
    INDIA("in", "India"),
    INDONESIA("id", "Indonesia"),
    IRAN("ir", "Iran"),
    IRAQ("iq", "Iraq"),
    IRELAND("ie", "Ireland"),
    ISRAEL("il", "Israel"),
    ITALY("it", "Italy"),
    JAMAICA("jm", "Jamaica"),
    JAPAN("jp", "Japan"),
    JORDAN("jo", "Jordan"),
    KAZAKHSTAN("kz", "Kazakhstan"),
    KENYA("ke", "Kenya"),
    KIRIBATI("ki", "Kiribati"),
    KOSOVO("xk", "Kosovo"),
    KUWAIT("kw", "Kuwait"),
    KYRGYZSTAN("kg", "Kyrgyzstan"),
    LAOS("la", "Laos"),
    LATVIA("lv", "Latvia"),
    LEBANON("lb", "Lebanon"),
    LESOTHO("ls", "Lesotho"),
    LIBERIA("lr", "Liberia"),
    LIBYA("ly", "Libya"),
    LIECHTENSTEIN("li", "Liechtenstein"),
    LITHUANIA("lt", "Lithuania"),
    LUXEMBOURG("lu", "Luxembourg"),
    MACAO("mo", "Macao"),
    MADAGASCAR("mg", "Madagascar"),
    MALAWI("mw", "Malawi"),
    MALAYSIA("my", "Malaysia"),
    MALDIVES("mv", "Maldives"),
    MALI("ml", "Mali"),
    MALTA("mt", "Malta"),
    MARSHALL_ISLANDS("mh", "Marshall Islands"),
    MAURITANIA("mr", "Mauritania"),
    MAURITIUS("mu", "Mauritius"),
    MEXICO("mx", "Mexico"),
    MICRONESIA("fm", "Micronesia"),
    MOLDOVA("md", "Moldova"),
    MONACO("mc", "Monaco"),
    MONGOLIA("mn", "Mongolia"),
    MONTENEGRO("me", "Montenegro"),
    MOROCCO("ma", "Morocco"),
    MOZAMBIQUE("mz", "Mozambique"),
    MYANMAR("mm", "Myanmar"),
    NAMIBIA("na", "Namibia"),
    NAURU("nr", "Nauru"),
    NEPAL("np", "Nepal"),
    NETHERLANDS("nl", "Netherlands"),
    NEW_ZEALAND("nz", "New Zealand"),
    NICARAGUA("ni", "Nicaragua"),
    NIGER("ne", "Niger"),
    NIGERIA("ng", "Nigeria"),
    NORTH_KOREA("kp", "North Korea"),
    NORTH_MACEDONIA("mk", "North Macedonia"),
    NORWAY("no", "Norway"),
    OMAN("om", "Oman"),
    PAKISTAN("pk", "Pakistan"),
    PALAU("pw", "Palau"),
    PALESTINIAN_TERRITORIES("ps", "Palestinian Territories"),
    PANAMA("pa", "Panama"),
    PAPUA_NEW_GUINEA("pg", "Papua New Guinea"),
    PARAGUAY("py", "Paraguay"),
    PERU("pe", "Peru"),
    PHILIPPINES("ph", "Philippines"),
    POLAND("pl", "Poland"),
    PORTUGAL("pt", "Portugal"),
    QATAR("qa", "Qatar"),
    ROMANIA("ro", "Romania"),
    RUSSIAN_FEDERATION("ru", "Russian Federation"),
    RWANDA("rw", "Rwanda"),
    SAINT_KITTS_AND_NEVIS("kn", "Saint Kitts and Nevis"),
    SAINT_LUCIA("lc", "Saint Lucia"),
    SAMOA("ws", "Samoa"),
    SAN_MARINO("sm", "San Marino"),
    SAO_TOME_AND_PRINCIPE("st", "Sao Tome and Principe"),
    SAUDI_ARABIA("sa", "Saudi Arabia"),
    SENEGAL("sn", "Senegal"),
    SERBIA("rs", "Serbia"),
    SEYCHELLES("sc", "Seychelles"),
    SIERRA_LEONE("sl", "Sierra Leone"),
    SINGAPORE("sg", "Singapore"),
    SLOVAKIA("sk", "Slovakia"),
    SLOVENIA("si", "Slovenia"),
    SOLOMON_ISLANDS("sb", "Solomon Islands"),
    SOMALIA("so", "Somalia"),
    SOUTH_AFRICA("za", "South Africa"),
    SOUTH_KOREA("kr", "South Korea"),
    SOUTH_SUDAN("ss", "South Sudan"),
    SPAIN("es", "Spain"),
    SRI_LANKA("lk", "Sri Lanka"),
    ST_VINCENT_AND_THE_GRENADINES("vc", "St. Vincent and the Grenadines"),
    SUDAN("sd", "Sudan"),
    SURINAME("sr", "Suriname"),
    SWEDEN("se", "Sweden"),
    SWITZERLAND("ch", "Switzerland"),
    SYRIA("sy", "Syria"),
    TAIWAN("tw", "Taiwan"),
    TAJIKISTAN("tj", "Tajikistan"),
    TANZANIA("tz", "Tanzania"),
    THAILAND("th", "Thailand"),
    TIMOR_LESTE("tl", "Timor-Leste"),
    TOGO("tg", "Togo"),
    TONGA("to", "Tonga"),
    TRINIDAD_AND_TOBAGO("tt", "Trinidad and Tobago"),
    TUNISIA("tn", "Tunisia"),
    TURKEY("tr", "Türkiye"),
    TURKMENISTAN("tm", "Turkmenistan"),
    TUVALU("tv", "Tuvalu"),
    UGANDA("ug", "Uganda"),
    UKRAINE("ua", "Ukraine"),
    UNITED_ARAB_EMIRATES("us", "United States of America"),
    URUGUAY("uy", "Uruguay"),
    UZBEKISTAN("uz", "Uzbekistan"),
    VANUATU("vu", "Vanuatu"),
    VATICAN_CITY("va", "Vatican City"),
    VENEZUELA("ve", "Venezuela"),
    VIETNAM("vn", "Viet Nam"),
    YEMEN("ye", "Yemen"),
    ZAMBIA("zm", "Zambia"),
    ZIMBABWE("zw", "Zimbabwe");

    companion object {
        val countryList = enumValues<Country>().toList()
    }
}